# Generated by Django 6.0.1 on 2026-01-28 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_ventagarage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habilidad',
            name='nivel',
            field=models.IntegerField(help_text='Nivel del 1 al 10'),
        ),
    ]
