# Generated by Django 6.0.1 on 2026-01-28 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_habilidad_nivel'),
    ]

    operations = [
        migrations.AddField(
            model_name='educacion',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='educaciones', to='cv.perfil'),
        ),
        migrations.AddField(
            model_name='experiencia',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experiencias', to='cv.perfil'),
        ),
        migrations.AddField(
            model_name='habilidad',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='habilidades', to='cv.perfil'),
        ),
        migrations.AddField(
            model_name='referencia',
            name='perfil',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referencias', to='cv.perfil'),
        ),
    ]
